;
; Part of the listing generated by Microsoft (R) Optimizing Compiler :p
;
;   uint64_t factorial(uint64_t n) {
;       return (n <= 1) ? 1 : n * factorial(n-1);
;   }
;
        global  factorial

        section .text

factorial:				; COMDAT

	push	rbx
	sub	rsp, 32			; stack register

	mov	eax, 1
	mov	rbx, rcx
	cmp	rcx, rax                ; n < 1?
	jb	SHORT return
	dec	rcx                     ; n - 1
	call	factorial               ; recursion
	imul	rax, rbx
return:
	add	rsp, 32			; stack register
	pop	rbx

	ret
